### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#516]
## Description

- Blocked by https://github.com/zarr-developers/numcodecs/issues/377
  ```shell
		  numcodecs/blosc.c:308:12: fatal error: longintrepr.h: No such file or directory
			308 |   #include "longintrepr.h"
				|            ^~~~~~~~~~~~~~~
		  compilation terminated.
		  [numcodecs] command '/usr/bin/gcc' failed with exit code 1
		  Traceback (most recent call last):
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 186, in _compile
			  self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1007, in spawn
			  spawn(cmd, dry_run=self.dry_run, **kwargs)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
			  raise DistutilsExecError(
		  distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1
		  
		  During handling of the above exception, another exception occurred:
		  
		  Traceback (most recent call last):
			File "/tmp/pip-install-17ujq63p/numcodecs_a2b3dd698830446596639f2a56a6c9ff/setup.py", line 301, in build_extension
			  build_ext.build_extension(self, ext)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
			  objects = self.compiler.compile(
						^^^^^^^^^^^^^^^^^^^^^^
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
			  self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
			  raise CompileError(msg)
		  distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1
		  
		  During handling of the above exception, another exception occurred:
		  
		  Traceback (most recent call last):
			File "<string>", line 2, in <module>
			File "<pip-setuptools-caller>", line 34, in <module>
			File "/tmp/pip-install-17ujq63p/numcodecs_a2b3dd698830446596639f2a56a6c9ff/setup.py", line 380, in <module>
			  run_setup(with_extensions)
			File "/tmp/pip-install-17ujq63p/numcodecs_a2b3dd698830446596639f2a56a6c9ff/setup.py", line 326, in run_setup
			  setup(
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
			  return distutils.core.setup(**attrs)
					 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
			  return run_commands(dist)
					 ^^^^^^^^^^^^^^^^^^
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
			  dist.run_commands()
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
			  self.run_command(cmd)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
			  super().run_command(command)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
			  cmd_obj.run()
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/command/install.py", line 68, in run
			  return orig.install.run(self)
					 ^^^^^^^^^^^^^^^^^^^^^^
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 698, in run
			  self.run_command('build')
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
			  self.distribution.run_command(command)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
			  super().run_command(command)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
			  cmd_obj.run()
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
			  self.run_command(cmd_name)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
			  self.distribution.run_command(command)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
			  super().run_command(command)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
			  cmd_obj.run()
			File "/tmp/pip-install-17ujq63p/numcodecs_a2b3dd698830446596639f2a56a6c9ff/setup.py", line 294, in run
			  build_ext.run(self)
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
			  self.build_extensions()
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
			  self._build_extensions_serial()
			File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
			  self.build_extension(ext)
			File "/tmp/pip-install-17ujq63p/numcodecs_a2b3dd698830446596639f2a56a6c9ff/setup.py", line 304, in build_extension
			  raise BuildFailed()
		  BuildFailed
		  [end of output]
	  
	  note: This error originates from a subprocess, and is likely not a problem with pip.
	error: legacy-install-failure

	× Encountered error while trying to install package.
	╰─> numcodecs

  ```

**Comment by fmigneault** [comment]
Supported for some time already. Example successful tests: 
https://github.com/crim-ca/weaver/actions/runs/5115545361/jobs/9196910056
https://github.com/crim-ca/weaver/actions/runs/5115545361/jobs/9196910089
